package org.example.foodiebackend;

import org.example.foodiebackend.model.*;
import org.example.foodiebackend.repository.RecipeRepository;
import org.example.foodiebackend.repository.RoleRepository;
import org.example.foodiebackend.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.*;

@SpringBootApplication
@EnableScheduling
public class FoodieBackendApplication {

    @Autowired
    UserRepository userRepository;
    @Autowired
    RecipeRepository recipeRepository;
    @Autowired
    RoleRepository roleRepository;
    @Autowired
    PasswordEncoder passwordEncoder;

    public static void main(String[] args) {
        SpringApplication.run(FoodieBackendApplication.class, args);
    }

    @Bean
    CommandLineRunner initDatabase() {
        return args -> {
            List<Recipe> recipes = recipeRepository.findAll();
            if(recipes.size() < 50) {
                Role role = new Role(ERole.ROLE_USER);
                Role role1 = new Role(ERole.ROLE_MODERATOR);
                Role role2 = new Role(ERole.ROLE_ADMIN);
                roleRepository.saveAll(Arrays.asList(role, role1, role2));
                String image = "https://res.cloudinary.com/drsuzbfwz/image/upload/v1716985533/ikztxwmwddt9radsyrwl.jpg";
                User user = new User("Admin", "Admin", "admin@gmail.com", "admin", passwordEncoder.encode("admin"));

                user.setImagePublicId(image);
                Set<Role> roles = user.getRoles();
                Role userRole = roleRepository.findByName(ERole.ROLE_USER).get();
                roles.add(userRole);
                user.setRoles(roles);
                userRepository.save(user);
                Recipe recipe1 = new Recipe("Vegetable Fried Rice", "rice, carrots, peas, corn, green beans, soy sauce, garlic, eggs", "A flavorful and satisfying vegetarian fried rice dish.", "Cook rice according to package instructions, set aside, heat oil in a large skillet or wok, sauté garlic briefly, add vegetables and stir-fry until tender-crisp, push vegetables to the side, scramble eggs in the open space, combine eggs and vegetables, add cooked rice and soy sauce, toss everything together until well combined and heated through.", Category.VEG, "Asian", MealType.LUNCH, "Vegetarian", "Low-Fat", 30, 4, "https://www.youtube.com/watch?v=abcdefghijk", user, image); recipe1.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe1), new Nutrition("Carbohydrates", 45, recipe1), new Nutrition("Protein", 10, recipe1))));
                Recipe recipe2 = new Recipe("Tofu Fried Rice", "tofu, rice, carrots, peas, green beans, soy sauce, garlic", "A vegan-friendly fried rice dish with tofu and mixed vegetables.", "Cook rice according to package instructions, set aside, heat oil in a large skillet or wok, sauté garlic briefly, add tofu and vegetables and stir-fry until tender-crisp, add cooked rice and soy sauce, toss everything together until well combined and heated through.", Category.VEGAN, "Asian", MealType.LUNCH, "Vegan", "Low-Fat", 30, 4, "https://www.youtube.com/watch?v=lmnopqrstuvw", user, image); recipe2.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 280, recipe2), new Nutrition("Carbohydrates", 40, recipe2), new Nutrition("Protein", 12, recipe2))));
                Recipe recipe3 = new Recipe("Quinoa Salad", "quinoa, cucumber, tomatoes, feta cheese, red onion, lemon juice, olive oil, parsley", "A refreshing and protein-rich salad made with fluffy quinoa and fresh vegetables.", "Cook quinoa according to package instructions, let cool, combine cooked quinoa with diced cucumber, tomatoes, crumbled feta cheese, and sliced red onion in a large bowl, dress with a vinaigrette made from lemon juice, olive oil, salt, and pepper, toss to combine, garnish with chopped parsley.", Category.VEG, "Mediterranean", MealType.LUNCH, "Vegetarian", "High-Protein", 20, 4, "https://www.youtube.com/watch?v=xyzyabcdefgh", user, image); recipe3.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe3), new Nutrition("Protein", 12, recipe3), new Nutrition("Fiber", 5, recipe3))));
                Recipe recipe4 = new Recipe("Tabbouleh Salad", "bulgur, parsley, tomatoes, lemon juice, olive oil, mint", "A traditional Middle Eastern salad made with bulgur, parsley, tomatoes, and fresh herbs.", "Cook bulgur according to package instructions, let cool, combine cooked bulgur with diced tomatoes, chopped parsley, chopped mint, and sliced red onion in a large bowl, dress with a vinaigrette made from lemon juice, olive oil, salt, and pepper, toss to combine.", Category.VEG, "Middle Eastern", MealType.LUNCH, "Vegan", "High-Fiber", 15, 6, "https://www.youtube.com/watch?v=ijklmnopqrst", user, image); recipe4.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 200, recipe4), new Nutrition("Carbohydrates", 35, recipe4), new Nutrition("Fiber", 8, recipe4))));
                Recipe recipe5 = new Recipe("Lentil Soup", "lentils, carrots, celery, onions, vegetable broth, tomato paste, cumin, bay leaves", "A comforting and hearty lentil soup, perfect for chilly days.", "Rinse lentils, sauté onions, carrots, and celery in a pot with olive oil until softened, add lentils, vegetable broth, tomato paste, cumin, bay leaves, and salt and pepper to taste, bring to a boil, then reduce heat and simmer until lentils are tender, about 30 minutes, remove bay leaves before serving.", Category.VEG, "Middle Eastern", MealType.LUNCH, "Vegan", "High-Fiber", 45, 6, "https://www.youtube.com/watch?v=uvwxyzabcdef", user, image); recipe5.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 200, recipe5), new Nutrition("Protein", 12, recipe5), new Nutrition("Fiber", 10, recipe5))));
                Recipe recipe6 = new Recipe("Vegetable Lasagna", "lasagna noodles, spinach, mushrooms, ricotta cheese, mozzarella cheese, tomato sauce", "A hearty and comforting vegetarian lasagna loaded with fresh veggies.", "Cook lasagna noodles according to package instructions, in a baking dish, layer noodles, ricotta cheese, sautéed spinach and mushrooms, tomato sauce, and shredded mozzarella cheese, repeat layers until all ingredients are used, bake at 375°F for 30-40 minutes until cheese is melted and bubbly.", Category.VEG, "Italian", MealType.DINNER, "Vegetarian", "High-Protein", 60, 8, null, user, image); recipe6.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 450, recipe6), new Nutrition("Protein", 25, recipe6), new Nutrition("Fiber", 6, recipe6))));
                Recipe recipe7 = new Recipe("Chickpea Curry", "chickpeas, coconut milk, tomatoes, onions, garlic, ginger, curry powder", "A flavorful and protein-packed vegan curry with chickpeas and aromatic spices.", "Sauté onions, garlic, and ginger in a pot with olive oil until fragrant, add curry powder and cook for 1 minute, add diced tomatoes and coconut milk, bring to a simmer, add chickpeas and simmer for 20-25 minutes, season with salt and pepper, garnish with fresh cilantro.", Category.VEGAN, "Indian", MealType.DINNER, "Vegan", "High-Protein", 30, 4, "https://www.youtube.com/watch?v=abcdefghijk", user, image); recipe7.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe7), new Nutrition("Protein", 15, recipe7), new Nutrition("Fiber", 10, recipe7))));
                Recipe recipe8 = new Recipe("Quinoa Buddha Bowl", "quinoa, kale, sweet potatoes, avocado, chickpeas, tahini dressing", "A nutrient-dense and filling Buddha bowl with quinoa, roasted veggies, and a creamy tahini dressing.", "Cook quinoa according to package instructions, roast diced sweet potatoes in the oven until tender, massage kale with a bit of olive oil and lemon juice, arrange quinoa, roasted sweet potatoes, avocado slices, and chickpeas in a bowl, drizzle with tahini dressing made from tahini, lemon juice, water, and garlic.", Category.VEGAN, "American", MealType.LUNCH, "Vegan", "High-Protein", 45, 2, null, user, image); recipe8.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 500, recipe8), new Nutrition("Protein", 20, recipe8), new Nutrition("Fiber", 15, recipe8))));
                Recipe recipe9 = new Recipe("Grilled Salmon with Asparagus", "salmon fillets, asparagus, lemon, garlic, olive oil, salt, pepper", "A simple and delicious grilled salmon dish served with fresh asparagus.", "Preheat grill to medium-high heat, brush salmon fillets and asparagus with olive oil, season with salt, pepper, and garlic powder, grill salmon for 6-8 minutes per side, until cooked through, grill asparagus for 5-7 minutes, until tender, serve salmon and asparagus with lemon wedges.", Category.NON_VEG, "American", MealType.DINNER, "Pescatarian", "Low-Carb", 30, 2, "https://www.youtube.com/watch?v=lmnopqrstuvw", user, image); recipe9.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe9), new Nutrition("Protein", 30, recipe9), new Nutrition("Fat", 18, recipe9))));
                Recipe recipe10 = new Recipe("Chocolate Lava Cakes", "dark chocolate, butter, eggs, sugar, flour, cocoa powder", "Indulgent and decadent chocolate lava cakes with a molten center.", "Preheat oven to 400°F (205°C), grease ramekins with butter, melt chocolate and butter together, in a separate bowl, whisk eggs and sugar until light and fluffy, fold in the melted chocolate mixture and sifted flour, pour batter into ramekins and bake for 10-12 minutes, serve warm with a dusting of cocoa powder.", Category.DESSERT, "French", MealType.DESSERT, "Vegetarian", "High-Fat", 45, 4, "https://www.youtube.com/watch?v=xyzyabcdefgh", user, image); recipe10.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 500, recipe10), new Nutrition("Carbohydrates", 45, recipe10), new Nutrition("Fat", 35, recipe10))));
                Recipe recipe11 = new Recipe("Mediterranean Quinoa Salad", "quinoa, cherry tomatoes, cucumbers, red onion, feta cheese, parsley, lemon juice, olive oil", "A refreshing and protein-rich salad with quinoa, fresh veggies, and a tangy lemon dressing.", "Cook quinoa according to package instructions, let cool, combine cooked quinoa with diced cherry tomatoes, cucumbers, sliced red onion, crumbled feta cheese, and chopped parsley in a large bowl, dress with a vinaigrette made from lemon juice, olive oil, salt, and pepper, toss to combine.", Category.VEG, "Mediterranean", MealType.LUNCH, "Vegetarian", "High-Protein", 20, 4, null, user, image); recipe11.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe11), new Nutrition("Protein", 12, recipe11), new Nutrition("Fiber", 5, recipe11))));
                Recipe recipe12 = new Recipe("Spinach and Feta Stuffed Chicken", "chicken breasts, spinach, feta cheese, garlic, lemon juice, olive oil", "Juicy chicken breasts stuffed with a flavorful spinach and feta cheese mixture.", "Pound chicken breasts to flatten them, season with salt and pepper, in a bowl, mix together cooked spinach, crumbled feta cheese, minced garlic, and lemon juice, spoon the spinach mixture onto each chicken breast and roll up, brush with olive oil, bake at 375°F for 25-30 minutes until chicken is cooked through.", Category.NON_VEG, "Mediterranean", MealType.DINNER, "Vegetarian-Friendly", "High-Protein", 45, 4, "https://www.youtube.com/watch?v=abcdefghijk", user, image); recipe12.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe12), new Nutrition("Protein", 30, recipe12), new Nutrition("Fat", 15, recipe12))));
                Recipe recipe13 = new Recipe("Vegan Lentil and Sweet Potato Shepherd's Pie", "lentils, sweet potatoes, carrots, peas, vegetable broth, tomato paste, thyme", "A hearty and comforting vegan twist on the classic shepherd's pie.", "Cook lentils according to package instructions, in a saucepan, sauté diced carrots and peas in olive oil until tender, add cooked lentils, vegetable broth, tomato paste, and thyme, transfer to a baking dish, top with mashed sweet potatoes, bake at 375°F for 30 minutes until heated through.", Category.VEGAN, "American", MealType.DINNER, "Vegan", "High-Fiber", 60, 6, null, user, image); recipe13.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 400, recipe13), new Nutrition("Protein", 15, recipe13), new Nutrition("Fiber", 12, recipe13))));
                Recipe recipe14 = new Recipe("Cauliflower Crust Pizza", "cauliflower, eggs, mozzarella cheese, tomato sauce, basil, mushrooms", "A low-carb pizza with a delicious cauliflower-based crust.", "Grate cauliflower to create cauliflower rice, squeeze out excess moisture, mix with eggs and grated mozzarella cheese, press mixture onto a baking sheet to create a crust, bake at 400°F for 15 minutes, top with tomato sauce, sliced mushrooms, and fresh basil, bake for an additional 10-15 minutes until cheese is melted.", Category.VEG, "Italian", MealType.DINNER, "Low-Carb", "Vegetarian", 45, 4, "https://www.youtube.com/watch?v=lmnopqrstuvw", user, image); recipe14.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe14), new Nutrition("Carbohydrates", 20, recipe14), new Nutrition("Protein", 15, recipe14))));
                Recipe recipe15 = new Recipe("Banana Bread", "bananas, flour, sugar, eggs, butter, baking soda, vanilla extract", "A classic and delicious banana bread perfect for breakfast or a snack.", "Mash ripe bananas in a bowl, add melted butter, sugar, eggs, and vanilla extract, mix well, in a separate bowl, whisk together flour, baking soda, and salt, fold dry ingredients into wet ingredients until just combined, pour batter into a greased loaf pan, bake at 350°F for 55-60 minutes until a toothpick inserted in the center comes out clean.", Category.DESSERT, "American", MealType.BREAKFAST, "Vegetarian", "High-Carb", 75, 8, null, user, image); recipe15.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe15), new Nutrition("Carbohydrates", 40, recipe15), new Nutrition("Protein", 4, recipe15))));
                Recipe recipe16 = new Recipe("Vegetable Stir-Fry", "bell peppers, broccoli, carrots, snap peas, mushrooms, soy sauce, garlic, ginger", "A colorful and flavorful veggie stir-fry packed with nutrients.", "Heat a large skillet or wok over high heat, add oil, sauté garlic and ginger briefly, add all the vegetables and stir-fry until tender-crisp, add soy sauce and toss to combine, serve over steamed rice.", Category.VEGAN, "Asian", MealType.DINNER, "Vegan", "Low-Fat", 30, 4, null, user, image); recipe16.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 200, recipe16), new Nutrition("Carbohydrates", 25, recipe16), new Nutrition("Fiber", 8, recipe16))));
                Recipe recipe17 = new Recipe("Greek Salad", "tomatoes, cucumbers, red onion, feta cheese, Kalamata olives, oregano, lemon juice, olive oil", "A fresh and flavorful Greek salad with tangy feta cheese and Kalamata olives.", "In a large bowl, combine diced tomatoes, sliced cucumbers, sliced red onion, crumbled feta cheese, and Kalamata olives, dress with a vinaigrette made from lemon juice, olive oil, oregano, salt, and pepper, toss to combine.", Category.VEG, "Mediterranean", MealType.LUNCH, "Vegetarian", "Low-Carb", 15, 4, null, user, image); recipe17.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe17), new Nutrition("Fat", 18, recipe17), new Nutrition("Protein", 8, recipe17))));
                Recipe recipe18 = new Recipe("Turkey Meatballs with Zucchini Noodles", "ground turkey, zucchini, eggs, breadcrumbs, garlic, parsley, tomato sauce", "Lean turkey meatballs served over zucchini noodles for a low-carb and protein-packed meal.", "In a bowl, mix together ground turkey, eggs, breadcrumbs, minced garlic, and chopped parsley, form into meatballs, bake at 400°F for 15-18 minutes, in a skillet, heat tomato sauce, add cooked meatballs, serve over spiralized zucchini noodles.", Category.NON_VEG, "Italian", MealType.DINNER, "Low-Carb", "High-Protein", 45, 4, "https://www.youtube.com/watch?v=abcdefghijk", user, image); recipe18.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe18), new Nutrition("Protein", 30, recipe18), new Nutrition("Carbohydrates", 15, recipe18))));
                Recipe recipe19 = new Recipe("Overnight Oats", "rolled oats, almond milk, chia seeds, maple syrup, vanilla extract, mixed berries", "A make-ahead breakfast with layers of oats, almond milk, and fresh berries.", "In a jar or bowl, combine rolled oats, almond milk, chia seeds, maple syrup, and vanilla extract, stir well, refrigerate overnight, in the morning, top with fresh mixed berries and an extra drizzle of maple syrup if desired.", Category.BREAKFAST, "American", MealType.BREAKFAST, "Vegan", "High-Fiber", 10, 1, null, user, image); recipe19.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe19), new Nutrition("Carbohydrates", 45, recipe19), new Nutrition("Fiber", 8, recipe19))));
                Recipe recipe20 = new Recipe("Flourless Chocolate Cake", "dark chocolate, butter, eggs, sugar, cocoa powder", "A rich and decadent flourless chocolate cake that's naturally gluten-free.", "Preheat oven to 350°F, grease a springform pan, melt chocolate and butter together, in a separate bowl, whisk eggs and sugar until light and fluffy, fold in the melted chocolate mixture and cocoa powder, pour batter into prepared pan, bake for 25-30 minutes until set, let cool before serving.", Category.DESSERT, "French", MealType.DESSERT, "Gluten-Free", "High-Fat", 60, 10, "https://www.youtube.com/watch?v=lmnopqrstuvw", user, image); recipe20.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 400, recipe20), new Nutrition("Carbohydrates", 30, recipe20), new Nutrition("Fat", 30, recipe20))));
                Recipe recipe21 = new Recipe("Pesto Zucchini Noodles", "zucchini, basil pesto, cherry tomatoes, pine nuts, parmesan cheese", "A low-carb and refreshing zucchini noodle dish with homemade basil pesto.", "Spiralize zucchini to create zucchini noodles, toss with homemade or store-bought basil pesto, add halved cherry tomatoes and toasted pine nuts, top with grated parmesan cheese.", Category.VEG, "Italian", MealType.DINNER, "Low-Carb", "Vegetarian", 20, 2, null, user, image); recipe21.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe21), new Nutrition("Carbohydrates", 15, recipe21), new Nutrition("Fat", 20, recipe21))));
                Recipe recipe22 = new Recipe("Baked Oatmeal with Berries", "rolled oats, almond milk, eggs, maple syrup, mixed berries, vanilla extract", "A hearty and satisfying baked oatmeal with fresh berries.", "In a baking dish, mix together rolled oats, almond milk, eggs, maple syrup, and vanilla extract, fold in mixed berries, bake at 375°F for 30-35 minutes until set, serve warm.", Category.BREAKFAST, "American", MealType.BREAKFAST, "Vegetarian", "High-Fiber", 45, 6, null, user, image); recipe22.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe22), new Nutrition("Carbohydrates", 50, recipe22), new Nutrition("Protein", 10, recipe22))));
                Recipe recipe23 = new Recipe("Vegetarian Chili", "kidney beans, black beans, tomatoes, bell peppers, onions, garlic, chili powder, cumin", "A hearty and protein-packed vegetarian chili with a blend of beans and spices.", "In a large pot, sauté onions and garlic in olive oil until softened, add diced bell peppers and cook for a few minutes, add drained and rinsed kidney beans, black beans, diced tomatoes, chili powder, cumin, salt, and pepper, simmer for 20-30 minutes, garnish with avocado and cilantro.", Category.VEGAN, "Mexican", MealType.DINNER, "Vegan", "High-Fiber", 60, 6, null, user, image); recipe23.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe23), new Nutrition("Protein", 15, recipe23), new Nutrition("Fiber", 12, recipe23))));
                Recipe recipe24 = new Recipe("Caprese Salad", "tomatoes, fresh mozzarella cheese, basil, balsamic glaze, olive oil", "A classic Italian salad with fresh tomatoes, mozzarella, and basil.", "Slice tomatoes and fresh mozzarella cheese, arrange on a platter, scatter fresh basil leaves, drizzle with balsamic glaze and olive oil, season with salt and pepper.", Category.VEG, "Italian", MealType.LUNCH, "Vegetarian", "Low-Carb", 15, 4, null, user, image); recipe24.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe24), new Nutrition("Fat", 18, recipe24), new Nutrition("Protein", 10, recipe24))));
                Recipe recipe25 = new Recipe("Chocolate Avocado Mousse", "avocado, cocoa powder, maple syrup, vanilla extract, almond milk", "A rich and creamy chocolate mousse made with avocado for a healthy twist.", "In a food processor, blend together ripe avocado, cocoa powder, maple syrup, vanilla extract, and almond milk until smooth and creamy, chill before serving.", Category.DESSERT, "American", MealType.DESSERT, "Vegan", "High-Fiber", 15, 4, null, user, image); recipe25.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe25), new Nutrition("Carbohydrates", 30, recipe25), new Nutrition("Fat", 20, recipe25))));
                Recipe recipe26 = new Recipe("Avocado Toast with Egg", "whole grain bread, avocado, eggs, red pepper flakes, salt, pepper", "A protein-packed avocado toast topped with a fried egg.", "Toast bread slices, mash avocado and spread onto the toast, fry an egg sunny-side up, place the fried egg on top of the avocado toast, sprinkle with red pepper flakes, salt, and pepper.", Category.BREAKFAST, "American", MealType.BREAKFAST, "Vegetarian-Friendly", "High-Protein", 10, 2, null, user, image); recipe26.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe26), new Nutrition("Protein", 15, recipe26), new Nutrition("Fat", 20, recipe26))));
                Recipe recipe27 = new Recipe("Beef and Broccoli Stir-Fry", "sirloin steak, broccoli, carrots, bell peppers, soy sauce, garlic, ginger", "A classic Chinese-inspired beef and broccoli stir-fry.", "Slice sirloin steak into thin strips, stir-fry with minced garlic and ginger in a wok or large skillet, add broccoli, carrots, and bell peppers, stir-fry until vegetables are tender-crisp, add soy sauce and toss to combine, serve over steamed rice.", Category.NON_VEG, "Asian", MealType.DINNER, "Gluten-Free", "High-Protein", 30, 4, "https://www.youtube.com/watch?v=abcdefghijk", user, image); recipe27.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 400, recipe27), new Nutrition("Protein", 30, recipe27), new Nutrition("Carbohydrates", 20, recipe27))));
                Recipe recipe28 = new Recipe("Vegetable Fried Rice(new)", "rice, carrots, peas, corn, green beans, soy sauce, garlic, eggs", "A flavorful and satisfying vegetarian fried rice dish.", "Cook rice according to package instructions, set aside, heat oil in a large skillet or wok, sauté garlic briefly, add vegetables and stir-fry until tender-crisp, push vegetables to the side, scramble eggs in the open space, combine eggs and vegetables, add cooked rice and soy sauce, toss everything together until well combined and heated through.", Category.VEG, "Asian", MealType.LUNCH, "Vegetarian", "Low-Fat", 30, 4, null, user, image); recipe28.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe28), new Nutrition("Carbohydrates", 45, recipe28), new Nutrition("Protein", 10, recipe28))));
                Recipe recipe29 = new Recipe("Quinoa Salad(new)", "quinoa, cucumber, tomatoes, feta cheese, red onion, lemon juice, olive oil, parsley", "A refreshing and protein-rich salad made with fluffy quinoa and fresh vegetables.", "Cook quinoa according to package instructions, let cool, combine cooked quinoa with diced cucumber, tomatoes, crumbled feta cheese, and sliced red onion in a large bowl, dress with a vinaigrette made from lemon juice, olive oil, salt, and pepper, toss to combine, garnish with chopped parsley.", Category.VEG, "Mediterranean", MealType.LUNCH, "Vegetarian", "High-Protein", 20, 4, null, user, image); recipe29.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe29), new Nutrition("Protein", 12, recipe29), new Nutrition("Fiber", 5, recipe29))));
                Recipe recipe30 = new Recipe("Lentil Soup(new)", "lentils, carrots, celery, onions, vegetable broth, tomato paste, cumin, bay leaves", "A comforting and hearty lentil soup, perfect for chilly days.", "Rinse lentils, sauté onions, carrots, and celery in a pot with olive oil until softened, add lentils, vegetable broth, tomato paste, cumin, bay leaves, and salt and pepper to taste, bring to a boil, then reduce heat and simmer until lentils are tender, about 30 minutes, remove bay leaves before serving.", Category.VEG, "Middle Eastern", MealType.LUNCH, "Vegan", "High-Fiber", 45, 6, null, user, image); recipe30.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 200, recipe30), new Nutrition("Protein", 12, recipe30), new Nutrition("Fiber", 10, recipe30))));
                Recipe recipe31 = new Recipe("Chickpea Salad", "chickpeas, cucumber, tomatoes, red onion, feta cheese, lemon juice, olive oil, parsley", "A refreshing and protein-packed chickpea salad with fresh vegetables and herbs.", "Rinse and drain chickpeas, combine with diced cucumber, tomatoes, crumbled feta cheese, and sliced red onion in a large bowl, dress with a vinaigrette made from lemon juice, olive oil, salt, and pepper, toss to combine, garnish with chopped parsley.", Category.VEG, "Mediterranean", MealType.LUNCH, "Vegetarian", "High-Protein", 15, 4, "https://www.youtube.com/watch?v=abcdefghxyz", user, image); recipe31.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 220, recipe31), new Nutrition("Protein", 10, recipe31), new Nutrition("Fiber", 6, recipe31))));
                Recipe recipe32 = new Recipe("Mushroom Risotto", "arborio rice, mushrooms, onion, garlic, vegetable broth, white wine, Parmesan cheese, olive oil, parsley", "A creamy and savory risotto with mushrooms and Parmesan cheese.", "Heat oil in a large skillet, sauté diced onion and garlic until translucent, add sliced mushrooms and cook until tender, stir in arborio rice and cook for 1-2 minutes, deglaze with white wine, gradually add vegetable broth, stirring constantly, until rice is cooked and creamy, stir in grated Parmesan cheese, season with salt and pepper, garnish with chopped parsley.", Category.VEG, "Italian", MealType.DINNER, "Vegetarian", "Low-Fat", 40, 4, "https://www.youtube.com/watch?v=jklmnopqrst", user, image); recipe32.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe32), new Nutrition("Carbohydrates", 50, recipe32), new Nutrition("Protein", 12, recipe32))));
                Recipe recipe33 = new Recipe("Spinach and Feta Stuffed Peppers", "bell peppers, spinach, feta cheese, quinoa, onion, garlic, olive oil, salt, pepper", "Bell peppers stuffed with a flavorful mixture of quinoa, spinach, and feta cheese.", "Cook quinoa according to package instructions, set aside, heat oil in a skillet, sauté diced onion and garlic until translucent, add spinach and cook until wilted, combine cooked quinoa, spinach mixture, and crumbled feta cheese, season with salt and pepper, stuff halved bell peppers with the mixture, bake at 375°F for 20-25 minutes.", Category.VEG, "Mediterranean", MealType.DINNER, "Vegetarian", "Low-Fat", 35, 4, "https://www.youtube.com/watch?v=uvwxyzabcde", user, image); recipe33.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe33), new Nutrition("Carbohydrates", 30, recipe33), new Nutrition("Protein", 10, recipe33))));
                Recipe recipe34 = new Recipe("Black Bean Tacos", "black beans, corn tortillas, avocado, red cabbage, lime, cilantro, cumin, garlic powder, salt, pepper", "Tasty and nutritious black bean tacos with fresh avocado and crunchy cabbage.", "Rinse and drain black beans, season with cumin, garlic powder, salt, and pepper, heat in a skillet until warm, warm corn tortillas in a dry skillet, assemble tacos by filling tortillas with seasoned black beans, sliced avocado, shredded red cabbage, and fresh cilantro, squeeze lime juice over the top.", Category.VEGAN, "Mexican", MealType.LUNCH, "Vegan", "High-Fiber", 20, 4, "https://www.youtube.com/watch?v=fghijklmnop", user, image); recipe34.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 200, recipe34), new Nutrition("Carbohydrates", 30, recipe34), new Nutrition("Fiber", 10, recipe34))));
                Recipe recipe35 = new Recipe("Sweet Potato and Black Bean Chili", "sweet potatoes, black beans, tomatoes, onion, garlic, chili powder, cumin, vegetable broth, olive oil, salt, pepper", "A hearty and flavorful chili made with sweet potatoes and black beans.", "Heat oil in a large pot, sauté diced onion and garlic until translucent, add diced sweet potatoes and cook for 5-7 minutes, stir in black beans, diced tomatoes, vegetable broth, chili powder, and cumin, bring to a boil, reduce heat and simmer until sweet potatoes are tender, about 20 minutes, season with salt and pepper to taste.", Category.VEGAN, "American", MealType.DINNER, "Vegan", "High-Fiber", 40, 6, "https://www.youtube.com/watch?v=qrstuvwxyz", user, image); recipe35.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe35), new Nutrition("Carbohydrates", 50, recipe35), new Nutrition("Fiber", 12, recipe35))));
                Recipe recipe36 = new Recipe("Grilled Chicken Salad", "chicken breast, mixed greens, cherry tomatoes, cucumber, red onion, olive oil, lemon juice, salt, pepper", "A light and healthy grilled chicken salad with fresh vegetables.", "Season chicken breast with salt and pepper, grill until cooked through, let cool, and slice, combine mixed greens, halved cherry tomatoes, sliced cucumber, and red onion in a large bowl, top with sliced chicken, dress with a vinaigrette made from olive oil, lemon juice, salt, and pepper.", Category.NON_VEG, "American", MealType.LUNCH, "High-Protein", "Low-Fat", 25, 4, "https://www.youtube.com/watch?v=abcdefghijk1", user, image); recipe36.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe36), new Nutrition("Protein", 30, recipe36), new Nutrition("Carbohydrates", 10, recipe36))));
                Recipe recipe37 = new Recipe("Vegan Pancakes", "flour, almond milk, baking powder, maple syrup, vanilla extract, salt", "Fluffy and delicious vegan pancakes, perfect for breakfast.", "In a bowl, combine flour, baking powder, and salt, in another bowl, mix almond milk, maple syrup, and vanilla extract, pour wet ingredients into dry ingredients and mix until just combined, heat a non-stick skillet over medium heat, pour batter onto skillet and cook until bubbles form, flip and cook until golden brown.", Category.VEGAN, "American", MealType.BREAKFAST, "Vegan", "Low-Fat", 20, 4, "https://www.youtube.com/watch?v=abcdefghijk2", user, image); recipe37.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 200, recipe37), new Nutrition("Carbohydrates", 40, recipe37), new Nutrition("Protein", 5, recipe37))));
                Recipe recipe38 = new Recipe("Gluten-Free Banana Bread", "gluten-free flour, bananas, eggs, coconut oil, honey, baking soda, vanilla extract, salt", "A moist and flavorful gluten-free banana bread.", "Preheat oven to 350°F, in a bowl, mash bananas and mix with eggs, melted coconut oil, honey, and vanilla extract, add gluten-free flour, baking soda, and salt, mix until combined, pour batter into a greased loaf pan, bake for 60 minutes or until a toothpick comes out clean.", Category.GLUTEN, "American", MealType.BREAKFAST, "Gluten-Free", "Low-Fat", 70, 8, "https://www.youtube.com/watch?v=abcdefghijk3", user, image); recipe38.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 180, recipe38), new Nutrition("Carbohydrates", 30, recipe38), new Nutrition("Protein", 4, recipe38))));
                Recipe recipe39 = new Recipe("Chocolate Avocado Mousse", "ripe avocados, cocoa powder, maple syrup, vanilla extract, almond milk", "A rich and creamy chocolate mousse made with avocados.", "In a blender, combine ripe avocados, cocoa powder, maple syrup, vanilla extract, and almond milk, blend until smooth and creamy, chill in the refrigerator for at least 30 minutes before serving.", Category.DESSERT, "American", MealType.DESSERT, "Vegan", "Low-Fat", 15, 4, "https://www.youtube.com/watch?v=abcdefghijk4", user, image); recipe39.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe39), new Nutrition("Carbohydrates", 20, recipe39), new Nutrition("Protein", 3, recipe39))));
                Recipe recipe40 = new Recipe("Quinoa Breakfast Bowl", "quinoa, almond milk, berries, honey, chia seeds, almonds", "A nutritious and filling breakfast bowl with quinoa and fresh berries.", "Cook quinoa according to package instructions, set aside, in a bowl, combine cooked quinoa with almond milk, top with fresh berries, drizzle with honey, and sprinkle with chia seeds and sliced almonds.", Category.BREAKFAST, "American", MealType.BREAKFAST, "Vegetarian", "High-Protein", 15, 2, "https://www.youtube.com/watch?v=abcdefghijk5", user, image); recipe40.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe40), new Nutrition("Carbohydrates", 50, recipe40), new Nutrition("Protein", 10, recipe40))));
                Recipe recipe41 = new Recipe("Spicy Shrimp Tacos", "shrimp, corn tortillas, cabbage, avocado, lime, cilantro, chili powder, cumin, garlic powder, salt, pepper", "Flavorful and spicy shrimp tacos with fresh cabbage and avocado.", "Season shrimp with chili powder, cumin, garlic powder, salt, and pepper, cook in a skillet until pink and opaque, warm corn tortillas in a dry skillet, assemble tacos by filling tortillas with shrimp, shredded cabbage, sliced avocado, and fresh cilantro, squeeze lime juice over the top.", Category.NON_VEG, "Mexican", MealType.LUNCH, "High-Protein", "Low-Fat", 20, 4, "https://www.youtube.com/watch?v=abcdefghijk6", user, image); recipe41.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe41), new Nutrition("Protein", 20, recipe41), new Nutrition("Carbohydrates", 15, recipe41))));
                Recipe recipe42 = new Recipe("Vegan Buddha Bowl", "quinoa, chickpeas, sweet potatoes, spinach, avocado, tahini, lemon juice, garlic powder, salt, pepper", "A nourishing and colorful vegan Buddha bowl with quinoa, chickpeas, and vegetables.", "Cook quinoa and set aside, roast diced sweet potatoes in the oven with olive oil, salt, and pepper, assemble bowls with quinoa, roasted sweet potatoes, chickpeas, fresh spinach, and sliced avocado, drizzle with a dressing made from tahini, lemon juice, garlic powder, salt, and pepper.", Category.VEGAN, "American", MealType.LUNCH, "Vegan", "High-Fiber", 30, 4, "https://www.youtube.com/watch?v=abcdefghijk7", user, image); recipe42.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 400, recipe42), new Nutrition("Carbohydrates", 60, recipe42), new Nutrition("Protein", 15, recipe42))));
                Recipe recipe43 = new Recipe("Greek Yogurt Parfait", "Greek yogurt, granola, berries, honey, chia seeds", "A simple and delicious Greek yogurt parfait with granola and fresh berries.", "In a bowl or glass, layer Greek yogurt, granola, and fresh berries, drizzle with honey and sprinkle with chia seeds.", Category.BREAKFAST, "American", MealType.BREAKFAST, "Vegetarian", "High-Protein", 10, 2, "https://www.youtube.com/watch?v=abcdefghijk8", user, image); recipe43.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 250, recipe43), new Nutrition("Carbohydrates", 30, recipe43), new Nutrition("Protein", 15, recipe43))));
                Recipe recipe44 = new Recipe("Lentil Veggie Burgers", "lentils, breadcrumbs, carrot, onion, garlic, cumin, salt, pepper, olive oil, burger buns", "Hearty and nutritious lentil veggie burgers.", "Cook lentils according to package instructions, let cool, in a food processor, combine lentils, breadcrumbs, grated carrot, diced onion, minced garlic, cumin, salt, and pepper, form mixture into patties, heat olive oil in a skillet and cook patties until browned on both sides, serve on burger buns with your favorite toppings.", Category.VEGAN, "American", MealType.DINNER, "Vegan", "High-Fiber", 40, 4, "https://www.youtube.com/watch?v=abcdefghijk9", user, image); recipe44.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe44), new Nutrition("Carbohydrates", 50, recipe44), new Nutrition("Protein", 12, recipe44))));
                Recipe recipe45 = new Recipe("Chocolate Chia Pudding", "chia seeds, almond milk, cocoa powder, maple syrup, vanilla extract", "A creamy and healthy chocolate chia pudding.", "In a bowl, whisk together chia seeds, almond milk, cocoa powder, maple syrup, and vanilla extract, let sit for 5 minutes and whisk again to prevent clumping, cover and refrigerate for at least 2 hours or overnight.", Category.DESSERT, "American", MealType.DESSERT, "Vegan", "Low-Fat", 10, 2, "https://www.youtube.com/watch?v=abcdefghijk10", user, image); recipe45.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 200, recipe45), new Nutrition("Carbohydrates", 30, recipe45), new Nutrition("Protein", 5, recipe45))));
                Recipe recipe46 = new Recipe("Margherita Pizza", "pizza dough, tomatoes, fresh mozzarella, basil leaves, olive oil, salt", "A classic Margherita pizza with fresh tomatoes, mozzarella, and basil.", "Preheat oven to 475°F, roll out pizza dough on a floured surface, transfer to a baking sheet, spread sliced tomatoes over the dough, add slices of fresh mozzarella, drizzle with olive oil and sprinkle with salt, bake for 10-12 minutes until crust is golden and cheese is bubbly, top with fresh basil leaves before serving.", Category.VEG, "Italian", MealType.DINNER, "Vegetarian", "Low-Fat", 30, 4, "https://www.youtube.com/watch?v=pizzarecipe1", user, image); recipe46.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe46), new Nutrition("Carbohydrates", 40, recipe46), new Nutrition("Protein", 12, recipe46))));
                Recipe recipe47 = new Recipe("BBQ Chicken Pizza", "pizza dough, BBQ sauce, cooked chicken breast, red onion, mozzarella, cilantro", "A flavorful BBQ chicken pizza with red onions and cilantro.", "Preheat oven to 475°F, roll out pizza dough on a floured surface, transfer to a baking sheet, spread BBQ sauce over the dough, top with shredded cooked chicken, thinly sliced red onions, and shredded mozzarella, bake for 10-12 minutes until crust is golden and cheese is melted, sprinkle with fresh cilantro before serving.", Category.NON_VEG, "American", MealType.DINNER, "High-Protein", "Low-Fat", 30, 4, "https://www.youtube.com/watch?v=pizzarecipe2", user, image); recipe47.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 350, recipe47), new Nutrition("Carbohydrates", 40, recipe47), new Nutrition("Protein", 20, recipe47))));
                Recipe recipe48 = new Recipe("Vegan Veggie Pizza", "pizza dough, tomato sauce, bell peppers, red onion, mushrooms, spinach, vegan cheese", "A colorful and tasty vegan pizza loaded with fresh vegetables.", "Preheat oven to 475°F, roll out pizza dough on a floured surface, transfer to a baking sheet, spread tomato sauce over the dough, top with sliced bell peppers, red onion, mushrooms, spinach, and shredded vegan cheese, bake for 10-12 minutes until crust is golden and cheese is melted.", Category.VEGAN, "Italian", MealType.DINNER, "Vegan", "Low-Fat", 30, 4, "https://www.youtube.com/watch?v=pizzarecipe3", user, image); recipe48.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 280, recipe48), new Nutrition("Carbohydrates", 40, recipe48), new Nutrition("Protein", 8, recipe48))));
                Recipe recipe49 = new Recipe("Pepperoni Pizza", "pizza dough, tomato sauce, mozzarella, pepperoni slices, oregano", "A classic pepperoni pizza with melted mozzarella and savory pepperoni.", "Preheat oven to 475°F, roll out pizza dough on a floured surface, transfer to a baking sheet, spread tomato sauce over the dough, top with shredded mozzarella and pepperoni slices, sprinkle with oregano, bake for 10-12 minutes until crust is golden and cheese is melted and bubbly.", Category.NON_VEG, "Italian", MealType.DINNER, "High-Protein", "Low-Fat", 30, 4, "https://www.youtube.com/watch?v=pizzarecipe4", user, image); recipe49.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 400, recipe49), new Nutrition("Carbohydrates", 40, recipe49), new Nutrition("Protein", 18, recipe49))));
                Recipe recipe50 = new Recipe("Gluten-Free Pizza", "gluten-free pizza crust, tomato sauce, mozzarella, cherry tomatoes, basil, olive oil", "A delicious gluten-free pizza with fresh cherry tomatoes and basil.", "Preheat oven to 475°F, place gluten-free pizza crust on a baking sheet, spread tomato sauce over the crust, top with shredded mozzarella and halved cherry tomatoes, drizzle with olive oil, bake for 10-12 minutes until crust is golden and cheese is melted, top with fresh basil leaves before serving.", Category.GLUTEN, "Italian", MealType.DINNER, "Gluten-Free", "Low-Fat", 30, 4, "https://www.youtube.com/watch?v=pizzarecipe5", user, image); recipe50.setNutritions(new HashSet<>(Arrays.asList(new Nutrition("Calories", 300, recipe50), new Nutrition("Carbohydrates", 35, recipe50), new Nutrition("Protein", 10, recipe50))));
                List<Recipe> recipeList = new ArrayList<>(Arrays.asList(recipe1, recipe2, recipe3, recipe4, recipe5, recipe6, recipe7, recipe8, recipe9, recipe10, recipe11, recipe12, recipe13, recipe14, recipe15, recipe16, recipe17, recipe18, recipe19, recipe20, recipe21, recipe22, recipe23, recipe24, recipe25, recipe26, recipe27, recipe28, recipe29, recipe30, recipe31, recipe32, recipe33, recipe34, recipe35, recipe36, recipe37, recipe38, recipe39, recipe40, recipe41, recipe42, recipe43, recipe44, recipe45, recipe46, recipe47, recipe48, recipe49, recipe50));
                recipeRepository.saveAll(recipeList);
            }
        };
    }
}
